version: "2"

linters:
  default: none
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - misspell
    - unparam
    - unconvert
    - gocritic
    - revive
  settings:
    revive:
      rules:
        - name: blank-imports
        - name: context-as-argument
        - name: context-keys-type
        - name: dot-imports
        - name: error-return
        - name: error-strings
        - name: error-naming
        - name: exported
        - name: increment-decrement
        - name: var-naming
        - name: var-declaration
        - name: package-comments
        - name: range
        - name: receiver-naming
        - name: time-naming
        - name: unexported-return
        - name: indent-error-flow
        - name: errorf
  exclusions:
    rules:
      - path: _test\.go
        linters:
          - errcheck
          - unparam
      - path: zz_generated
        linters:
          - all

formatters:
  enable:
    - gofmt
    - goimports
  settings:
    gofmt:
      simplify: true
    goimports:
      local-prefixes:
        - github.com/JeffResc/authentik-k8s-operator
  exclusions:
    rules:
      - path: zz_generated
        linters:
          - all
